### ISSUE TITLE
img node in HTML renderer

### ISSUE THREAD

**Issue by FouadRaheb** [ResaleAI/receipt-components#4]
Hello, 

Great packages, super useful!

Is it possible to render an img node in an HTML renderer?
Something similar to the @resaleai/receipt-image-node) but for browsers.

This with a way to have right and left text on the same line would make this library complete.

**Comment by FouadRaheb** [comment]
Sorry, I just found @resaleai/receipt-image-browser. It wasn't mentioned in the readme.

**Comment by zaviermiller** [comment]
Just seeing this, I am still working on the documentation, so it will be better in the future!
