### ISSUE TITLE
Can not register receipt-image-browser node to a component

### ISSUE THREAD

**Issue by FouadRaheb** [ResaleAI/receipt-components#5]
When registering imagePlugin node to a component

> import imagePlugin from "@resaleai/receipt-image-browser";
ReceiptComponent.registerNodes([imagePlugin]);

The page is throwing an error

>  ⨯ file:///.../node_modules/@resaleai/receipt-image-browser/dist/main.mjs:11
import { bytes, charToByte } from "@resaleai/receipt-escpos-renderer/util";
         ^^^^^
SyntaxError: The requested module '@resaleai/receipt-escpos-renderer/util' does not provide an export named 'bytes'

**Comment by zaviermiller** [comment]
Thanks for the report! I have made a PR to fix this issue and will merge it soon. I'll let you know when it's merged so you can update the version of the `receipt-image-browser` package you are using.

**Comment by FouadRaheb** [comment]
Thanks for the fast fix!
Great work on this library, exactly what I needed for my project.

**Comment by zaviermiller** [comment]
This issue is now fixed in version receipt-components@3.3.1 and receipt-image-browser@1.1.1

**Comment by FouadRaheb** [comment]
Thanks for the updates. The page does not throw this error now, but I'm getting an error when rendering to HTML.

> Unhandled Runtime Error
Error: Renderer for image not found

> htmlStr = await MovieReceipt.render<string>(receiptData, "HTML");

It is trying to render image and not img for some reason

https://github.com/ResaleAI/receipt-components/blob/b8de194a9d45d5b22b770401aadc9b9f459455e3/packages/renderers/receipt-html-renderer/src/renderer.ts#L69
